INSERT INTO "announcement" VALUES (1,'Civies day','There is civies day on friday','2026-05-12',2);
INSERT INTO "announcement" VALUES (2,'Music Class','The school will have a special music class on friday','2026-05-04',23);
INSERT INTO "announcement" VALUES (3,'Presentation Day on Friday','There is a presentation day on friday','2026-05-19',23);
INSERT INTO "assessment" VALUES (1,'Chapter 3 Test ','2026-05-13',1);
INSERT INTO "assessment" VALUES (2,'EMS class test 1','2026-05-14',12);
INSERT INTO "assessment" VALUES (3,'Economics assignment 1','2026-05-11',14);
INSERT INTO "assessment" VALUES (4,'Accounting test 1','2026-05-12',28);
INSERT INTO "assessment" VALUES (5,'English test 1','2026-05-12',8);
INSERT INTO "assessment" VALUES (6,'Accounting class test 1','2026-05-06',50);
INSERT INTO "assessment" VALUES (7,'Accounting class test 1','2026-05-12',51);
INSERT INTO "assessment" VALUES (9,'Accounting moc exam','2026-05-22',50);
INSERT INTO "attendance" VALUES (1,14,1,'2026-05-13','Present');
INSERT INTO "attendance" VALUES (2,15,1,'2026-05-13','Absent');
INSERT INTO "attendance" VALUES (3,12,51,'2026-05-11','Present');
INSERT INTO "attendance" VALUES (4,21,13,'2026-05-12','Present');
INSERT INTO "attendance" VALUES (5,10,50,'2026-05-14','Present');
INSERT INTO "attendance" VALUES (6,11,50,'2026-05-12','Present');
INSERT INTO "attendance" VALUES (7,13,51,'2026-05-19','Present');
INSERT INTO "attendance" VALUES (8,12,51,'2026-05-19','Absent');
INSERT INTO "class" VALUES (1,'10A',10);
INSERT INTO "class" VALUES (2,'8A',8);
INSERT INTO "class" VALUES (3,'8B',8);
INSERT INTO "class" VALUES (4,'9A',9);
INSERT INTO "class" VALUES (5,'9B',9);
INSERT INTO "class" VALUES (6,'10B',10);
INSERT INTO "class" VALUES (7,'11A',11);
INSERT INTO "class" VALUES (8,'11B',11);
INSERT INTO "class" VALUES (9,'12A',12);
INSERT INTO "class" VALUES (10,'12B',12);
INSERT INTO "mark" VALUES (1,14,1,78);
INSERT INTO "mark" VALUES (2,15,1,57);
INSERT INTO "mark" VALUES (3,21,2,34);
INSERT INTO "mark" VALUES (4,1,3,99);
INSERT INTO "mark" VALUES (5,10,6,78);
INSERT INTO "mark" VALUES (6,11,6,67);
INSERT INTO "mark" VALUES (8,10,9,67);
INSERT INTO "mark" VALUES (9,12,7,89);
INSERT INTO "meeting" VALUES (1,1,2,'2026-05-14','14:00','Child discipline');
INSERT INTO "meeting" VALUES (2,2,2,'2026-05-15','13:00','Civies day');
INSERT INTO "meeting" VALUES (3,2,1,'2026-05-14','13:00','poor perfomance of child');
INSERT INTO "meeting" VALUES (4,17,23,'2026-05-14','13:00','Child progress');
INSERT INTO "meeting" VALUES (6,17,23,'2026-05-21','11:15','Absenteesm');
INSERT INTO "parent" VALUES (1,'Teressa','Nduna','bullieteressa@outlook.com','asdi@');
INSERT INTO "parent" VALUES (2,'Sibusiso','Dlamini','sibusisodlamini@gmail.com','123');
INSERT INTO "parent" VALUES (3,'Patrick','Mokoena','patrickmokoena@gmail.com','123');
INSERT INTO "parent" VALUES (4,'Grace','Buthelezi','gracebuthelezi@gmail.com','123');
INSERT INTO "parent" VALUES (5,'Joseph','Cele','josephcele@gmail.com','123');
INSERT INTO "parent" VALUES (6,'Simon','Khumalo','simonkhumalo@gmail.com','123');
INSERT INTO "parent" VALUES (7,'Elizabeth','Mahlangu','elizabethmahlangu@gmail.com','123');
INSERT INTO "parent" VALUES (8,'Rebecca','Sekhukhune','rebeccasekhukhune@gmail.com','123');
INSERT INTO "parent" VALUES (9,'Margeret','Mandonsela','margeretmandonsela@gmail.com','123');
INSERT INTO "parent" VALUES (10,'Samuel','Mbatha','samuelmbatha@gmail.com','123');
INSERT INTO "parent" VALUES (11,'David','Xulu','davidxulu@gmail.com','123');
INSERT INTO "parent" VALUES (12,'Patricia','Xulu','patriciaxulu@gmail.com','123');
INSERT INTO "parent" VALUES (13,'Richard','Phiri','richardphiri@gmail.com','123');
INSERT INTO "parent" VALUES (14,'Agnes','Phiri','agnesphiri@gmail.com','123');
INSERT INTO "parent" VALUES (15,'Cyril','Ramaphosa','cyrilramaphosa@gmail.com','123');
INSERT INTO "parent" VALUES (16,'Nomathemba','Ramaphosa','nomathembaramaphosa@gmail.com','123');
INSERT INTO "parent" VALUES (17,'Reuben','Mbuli','reubenmbuli@gmail.com','123');
INSERT INTO "student" VALUES (1,'Junior ','Mbuli','10',1);
INSERT INTO "student" VALUES (3,'Luyanda','Nduna','10',1);
INSERT INTO "student" VALUES (4,'Sipho','Dlamini','10',6);
INSERT INTO "student" VALUES (5,'Nandi','Mokoena','10',6);
INSERT INTO "student" VALUES (6,'Sibusiso','Buthelezi','11',7);
INSERT INTO "student" VALUES (7,'Bongekile','Cele','11',7);
INSERT INTO "student" VALUES (8,'Ayanda','Khumalo','11',8);
INSERT INTO "student" VALUES (9,'Kagiso','Mahlangu','11',8);
INSERT INTO "student" VALUES (10,'Zanele','Sekhukhune','12',9);
INSERT INTO "student" VALUES (11,'Simphiwe','Madonsela','12',9);
INSERT INTO "student" VALUES (12,'Mandla','Mbuli','12',10);
INSERT INTO "student" VALUES (13,'Bheki','Xulu','12',10);
INSERT INTO "student" VALUES (14,'Nokuthula','Mabaso','8',2);
INSERT INTO "student" VALUES (15,'Naledi','Phiri','8',2);
INSERT INTO "student" VALUES (16,'Refilwe','Ramaphosa','8',3);
INSERT INTO "student" VALUES (17,'Lindokuhle','Dlamini','8',3);
INSERT INTO "student" VALUES (18,'Vuyani','Mokoena','9',4);
INSERT INTO "student" VALUES (19,'Karabo','Khumalo','9',4);
INSERT INTO "student" VALUES (20,'Tshepo','Ramaphosa','9',5);
INSERT INTO "student" VALUES (21,'Nomsa','Mbuli','9',5);
INSERT INTO "subject" VALUES (1,'English HL',2,2);
INSERT INTO "subject" VALUES (2,'Mathematics',1,2);
INSERT INTO "subject" VALUES (3,'Afrikaans FAL',3,2);
INSERT INTO "subject" VALUES (4,'Mathematics',1,3);
INSERT INTO "subject" VALUES (5,'Natural Sciences',4,4);
INSERT INTO "subject" VALUES (6,'Life Orientation',5,2);
INSERT INTO "subject" VALUES (7,'Life Orientation',5,4);
INSERT INTO "subject" VALUES (8,'English HL',2,3);
INSERT INTO "subject" VALUES (9,'Afrikaans FAL',3,3);
INSERT INTO "subject" VALUES (10,'Natural Sciences',4,5);
INSERT INTO "subject" VALUES (11,'Life Orientation',5,3);
INSERT INTO "subject" VALUES (12,'EMS',6,4);
INSERT INTO "subject" VALUES (13,'EMS',6,5);
INSERT INTO "subject" VALUES (14,'Economics',6,1);
INSERT INTO "subject" VALUES (15,'Technology',7,2);
INSERT INTO "subject" VALUES (16,'Technology',7,3);
INSERT INTO "subject" VALUES (17,'IT',7,1);
INSERT INTO "subject" VALUES (18,'Social Sciences',8,4);
INSERT INTO "subject" VALUES (19,'Social Sciences',8,5);
INSERT INTO "subject" VALUES (20,'History',8,6);
INSERT INTO "subject" VALUES (21,'Creative Arts',9,2);
INSERT INTO "subject" VALUES (22,'Creative Arts',9,3);
INSERT INTO "subject" VALUES (23,'Mathematics',10,4);
INSERT INTO "subject" VALUES (24,'Mathematics',10,5);
INSERT INTO "subject" VALUES (25,'English HL',11,4);
INSERT INTO "subject" VALUES (26,'English HL',11,5);
INSERT INTO "subject" VALUES (27,'English HL',11,1);
INSERT INTO "subject" VALUES (28,'Accounting',12,1);
INSERT INTO "subject" VALUES (29,'Accounting',12,6);
INSERT INTO "subject" VALUES (30,'Physical Sciences',13,7);
INSERT INTO "subject" VALUES (31,'Physical Sciences',13,8);
INSERT INTO "subject" VALUES (32,'Life Sciences',14,1);
INSERT INTO "subject" VALUES (33,'Life Sciences',14,6);
INSERT INTO "subject" VALUES (34,'Pure Mathematics',15,1);
INSERT INTO "subject" VALUES (35,'Pure Mathematics',15,6);
INSERT INTO "subject" VALUES (36,'Mathematics Literacy',16,7);
INSERT INTO "subject" VALUES (37,'Mathematics Literacy',16,8);
INSERT INTO "subject" VALUES (38,'Afrikaans FAL',17,1);
INSERT INTO "subject" VALUES (39,'Afrikaans FAL',17,6);
INSERT INTO "subject" VALUES (40,'Economics',18,9);
INSERT INTO "subject" VALUES (41,'Economics',18,10);
INSERT INTO "subject" VALUES (42,'History',19,7);
INSERT INTO "subject" VALUES (43,'History',19,8);
INSERT INTO "subject" VALUES (44,'IT',20,7);
INSERT INTO "subject" VALUES (45,'IT',20,8);
INSERT INTO "subject" VALUES (46,'English HL',21,7);
INSERT INTO "subject" VALUES (47,'English HL',21,8);
INSERT INTO "subject" VALUES (48,'Life Orientation',22,1);
INSERT INTO "subject" VALUES (49,'Life Orientation',22,6);
INSERT INTO "subject" VALUES (50,'Accounting',23,9);
INSERT INTO "subject" VALUES (51,'Accounting',23,10);
INSERT INTO "teacher" VALUES (1,'Buhle','Mndze','brianbuhlem@gmail.com','asdi@');
INSERT INTO "teacher" VALUES (2,'Themba','Zwane','thembazwane@gmail.com','123');
INSERT INTO "teacher" VALUES (3,'Rishaal','Naaidoo','rishaalnaaidoo@gmail.com',NULL);
INSERT INTO "teacher" VALUES (4,'Maharaj','Dlamini','maharajdlamini@gmail.com','123');
INSERT INTO "teacher" VALUES (5,'Devi','Sigh','devisigh@gmail.com',NULL);
INSERT INTO "teacher" VALUES (6,'Rajesh','Patil','rajeshpatil@gmail.com','123');
INSERT INTO "teacher" VALUES (7,'Dinesh','Govendor','dineshgovender@gmail.com','123');
INSERT INTO "teacher" VALUES (8,'Sihle','Mdluli','sihlemdluli@gmail.com','123');
INSERT INTO "teacher" VALUES (9,'Amanda','Sithole','amandasithole@gmail.com','123');
INSERT INTO "teacher" VALUES (10,'Amahle','Zulu','amahlezulu@gmail.com','123');
INSERT INTO "teacher" VALUES (11,'Thabiso','Rampedi','thabisorampedi@gmail.com','123');
INSERT INTO "teacher" VALUES (12,'Amkhitha','Sibamba','amkhithasibamba@gmail.com','123');
INSERT INTO "teacher" VALUES (13,'Philasande','Ndlovu','philasandendlovu@gmail.com','123');
INSERT INTO "teacher" VALUES (14,'Buntu','Mahlutshane','buntumahlutshane@gmail.com','123');
INSERT INTO "teacher" VALUES (15,'Thabo','Mathebula','thabomathebula@gmail.com','123');
INSERT INTO "teacher" VALUES (16,'Cecil','Van Wyk','cecilvanwyk@gmail.com','123');
INSERT INTO "teacher" VALUES (17,'Falakhe','Mthembu','falakhemthembu@gmail.com','123');
INSERT INTO "teacher" VALUES (18,'Lusanda','Nkosi','luyandankosi@gmail.com','123');
INSERT INTO "teacher" VALUES (19,'Shawn','Mogaladi','shawnmogaladi@gmail.com','123');
INSERT INTO "teacher" VALUES (20,'Siyabonga','Mofokeng','siyabongamofokeng@gmail.com','123');
INSERT INTO "teacher" VALUES (21,'Sphiwe','Ngcobo','sphiwengcobo@gmail.com','123');
INSERT INTO "teacher" VALUES (22,'Sthembiso','Magagula','sthembisomagagula@gmail.com','123');
INSERT INTO "teacher" VALUES (23,'Khensani','Langa','khensanilanga@gmail.com','123');
INSERT INTO "teacher" VALUES (24,'Kutlwano','Makhabane','kutlwanomakhabane@gmail.com','123');
INSERT INTO "teacher" VALUES (25,'Nonjabulo','Smith','nonjabulosmith@gmail.com','123');
INSERT INTO "teacher" VALUES (27,'Nonjabulo','Vilakazi','nonjabulovilakazi@gmail.com','123');
INSERT INTO "teacher_student" VALUES (23,10);
INSERT INTO "teacher_student" VALUES (23,11);
INSERT INTO "teacher_student" VALUES (23,12);
INSERT INTO "teacher_student" VALUES (23,13);
INSERT INTO "teacher_student" VALUES (1,14);
INSERT INTO "teacher_student" VALUES (1,15);
INSERT INTO "teacher_student" VALUES (1,16);
INSERT INTO "teacher_student" VALUES (1,17);
INSERT INTO "teacher_student" VALUES (2,14);
INSERT INTO "teacher_student" VALUES (2,15);
INSERT INTO "teacher_student" VALUES (2,16);
INSERT INTO "teacher_student" VALUES (2,17);
INSERT INTO "teacher_student" VALUES (3,14);
INSERT INTO "teacher_student" VALUES (3,15);
INSERT INTO "teacher_student" VALUES (3,16);
INSERT INTO "teacher_student" VALUES (3,17);
INSERT INTO "teacher_student" VALUES (5,14);
INSERT INTO "teacher_student" VALUES (5,15);
INSERT INTO "teacher_student" VALUES (5,16);
INSERT INTO "teacher_student" VALUES (5,17);
INSERT INTO "teacher_student" VALUES (5,18);
INSERT INTO "teacher_student" VALUES (5,19);
INSERT INTO "teacher_student" VALUES (6,1);
INSERT INTO "teacher_student" VALUES (6,3);
INSERT INTO "teacher_student" VALUES (6,18);
INSERT INTO "teacher_student" VALUES (6,19);
INSERT INTO "teacher_student" VALUES (6,20);
INSERT INTO "teacher_student" VALUES (6,21);
INSERT INTO "teacher_student" VALUES (8,4);
INSERT INTO "teacher_student" VALUES (8,5);
INSERT INTO "teacher_student" VALUES (8,18);
INSERT INTO "teacher_student" VALUES (8,19);
INSERT INTO "teacher_student" VALUES (8,20);
INSERT INTO "teacher_student" VALUES (8,21);
INSERT INTO "teacher_student" VALUES (9,14);
INSERT INTO "teacher_student" VALUES (9,15);
INSERT INTO "teacher_student" VALUES (9,16);
INSERT INTO "teacher_student" VALUES (9,17);
INSERT INTO "teacher_student" VALUES (10,18);
INSERT INTO "teacher_student" VALUES (10,19);
INSERT INTO "teacher_student" VALUES (10,20);
INSERT INTO "teacher_student" VALUES (10,21);
INSERT INTO "teacher_student" VALUES (11,1);
INSERT INTO "teacher_student" VALUES (11,3);
INSERT INTO "teacher_student" VALUES (11,18);
INSERT INTO "teacher_student" VALUES (11,19);
INSERT INTO "teacher_student" VALUES (11,20);
INSERT INTO "teacher_student" VALUES (11,21);
INSERT INTO "teacher_student" VALUES (12,1);
INSERT INTO "teacher_student" VALUES (12,3);
INSERT INTO "teacher_student" VALUES (12,4);
INSERT INTO "teacher_student" VALUES (12,5);
INSERT INTO "teacher_student" VALUES (13,6);
INSERT INTO "teacher_student" VALUES (13,7);
INSERT INTO "teacher_student" VALUES (13,8);
INSERT INTO "teacher_student" VALUES (13,9);
INSERT INTO "teacher_student" VALUES (14,1);
INSERT INTO "teacher_student" VALUES (14,3);
INSERT INTO "teacher_student" VALUES (14,4);
INSERT INTO "teacher_student" VALUES (14,5);
INSERT INTO "teacher_student" VALUES (15,1);
INSERT INTO "teacher_student" VALUES (15,3);
INSERT INTO "teacher_student" VALUES (15,4);
INSERT INTO "teacher_student" VALUES (15,5);
INSERT INTO "teacher_student" VALUES (16,6);
INSERT INTO "teacher_student" VALUES (16,7);
INSERT INTO "teacher_student" VALUES (16,8);
INSERT INTO "teacher_student" VALUES (16,9);
INSERT INTO "teacher_student" VALUES (17,1);
INSERT INTO "teacher_student" VALUES (17,3);
INSERT INTO "teacher_student" VALUES (17,4);
INSERT INTO "teacher_student" VALUES (17,5);
INSERT INTO "teacher_student" VALUES (18,10);
INSERT INTO "teacher_student" VALUES (18,11);
INSERT INTO "teacher_student" VALUES (18,12);
INSERT INTO "teacher_student" VALUES (18,13);
INSERT INTO "teacher_student" VALUES (19,6);
INSERT INTO "teacher_student" VALUES (19,7);
INSERT INTO "teacher_student" VALUES (19,8);
INSERT INTO "teacher_student" VALUES (19,9);
INSERT INTO "teacher_student" VALUES (20,6);
INSERT INTO "teacher_student" VALUES (20,7);
INSERT INTO "teacher_student" VALUES (20,8);
INSERT INTO "teacher_student" VALUES (20,9);
INSERT INTO "teacher_student" VALUES (21,6);
INSERT INTO "teacher_student" VALUES (21,7);
INSERT INTO "teacher_student" VALUES (21,8);
INSERT INTO "teacher_student" VALUES (21,9);
INSERT INTO "teacher_student" VALUES (22,1);
INSERT INTO "teacher_student" VALUES (22,3);
INSERT INTO "teacher_student" VALUES (22,4);
INSERT INTO "teacher_student" VALUES (22,5);
INSERT INTO "teacher_student" VALUES (25,14);
INSERT INTO "teacher_student" VALUES (25,15);
INSERT INTO "teacher_student" VALUES (25,16);
INSERT INTO "teacher_student" VALUES (25,17);
